### ISSUE TITLE
Re-licensing bench

### ISSUE THREAD

**Issue by hadley** [r-lib/bench#101]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/bench/graphs/contributors). @coatless, @HughParsonage, @jdblischak, @lorenzwalthert, would you permit us to re-license bench with the MIT license? If so, please comment "I agree" below.

* [x] [@coatless](https://github.com/r-lib/bench/commits?author=coatless)  
* [x] [@HughParsonage](https://github.com/r-lib/bench/commits?author=HughParsonage)  
* [x] [@jdblischak](https://github.com/r-lib/bench/commits?author=jdblischak)  
* [x] [@lorenzwalthert](https://github.com/r-lib/bench/commits?author=lorenzwalthert)

**Comment by jdblischak** [comment]
I agree

**Comment by HughParsonage** [comment]
I agree. Just a typo fix — no code committed.

**Comment by lorenzwalthert** [comment]
I agree.
