### ISSUE TITLE
Blog on tidyverse.org: broken link to Neil 2014?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-lib/bench#105]
Hi

On the tidyverse blog, https://www.tidyverse.org/blog/2018/06/bench-1.0.1/, the link to Neil 2014 seems broken? It directs to https://radfordneal.https//dynverse.github.io/dynverse/wordpress.com/2014/02/02/inaccurate-results-from-microbenchmark/

which doesn't work?

Thanks!

**Comment by jimhester** [comment]
The correct link is https://radfordneal.wordpress.com/2014/02/02/inaccurate-results-from-microbenchmark/, as it shows in the bench readme (https://github.com/r-lib/bench#features)

I have no idea what happened to the link in the blog post, will fix it thanks.
