### ISSUE TITLE
result slot always empty

### ISSUE THREAD

**Issue by jgilis** [r-lib/bench#117]
Hi,

No matter how I specify the `mark` call, the `results` slot in the output tibble is always empty.

How to output results?

Jeroen

**Comment by DavisVaughan** [comment]
Can you provide a reprex https://www.tidyverse.org/help/? It works fine for me

``` r
out <- bench::mark(1:5)

out
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 1:5           128ns    183ns  4581893.        0B        0

out$result
#> [[1]]
#> [1] 1 2 3 4 5
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jgilis** [comment]
Thanks for the fast reply @DavisVaughan.

I apologise, I did not read the documentation to the extent I should have, and failed to spot the setting `check = FALSE` not only avoids checking consistency but also removes the results.

I will close the comment right away, sorry for the inconvenience!
