### ISSUE TITLE
Set digits to be the maximum of the sig figs of any bench time

### ISSUE THREAD

**Issue by HughParsonage** [r-lib/bench#18]
Sorry for the poor title, an example:

```
cat(bench:::format.bench_time(c(20, 72.5) / 1000), sep = "\n")
  20ms
72.5ms
```
Desired:
```
20.0ms
72.5ms
```

Started a pull request but had to violate too many tests. I simply changed line 105 in time.R to

```r
  if (scientific) {
    res <- format(res, scientific = scientific, digits = digits, drop0trailing = TRUE, ...)
  } else {
    res <- formatC(res,
                   width = max(nchar(res, allowNA = TRUE, keepNA = FALSE)),
                   digits = digits,
                   format = "f")
  }
```

I could choose something like `digits - 2` but thought that was something best left to you if you agreed with this as an issue.

**Comment by jimhester** [comment]
Understood, however I think some care should go into how we want to display this, ideally it would use similar logic to tibble / pillar's default for floating point numbers.
