### ISSUE TITLE
Possibility of a "ratio/relative" column? + other thoughts

### ISSUE THREAD

**Issue by njtierney** [r-lib/bench#19]
Firstly, thanks for putting the time and energy into writing this package!

You asked for feedback on twitter, and I wanted to share some thoughts - let me know if you want me to explain them better or open up separate issues :)

1. Would it be possible to arrange the rows by speed, so that the slowest is on the bottom, and the fastest is on top? I understand that perhaps it is best to present the expressions in the order that you gave them to bench, so I completely understand if that is what you want to do.

2. Would it be possible to have a "relative/ratio" column, where the fastest row gets a value of "1", and then the other rows can be something like 1.2, 1.4, 10, 100, etc, for things that are, 20% slower, 40%, 10 times, 100 times faster, etc? I understand that this could be potentially misleading, and will depend on the value you want to use - the min, mean, median, max, etc, but this is something I often ask myself when I compare speedups.

3. Could bench help compare timings of functions across branches? This is something that @romainfrancois and I have discussed, I believe he coined the term "branchmark". Although perhaps that should be its own package.

**Comment by jimhester** [comment]
`summary(relative = TRUE)`

**Comment by njtierney** [comment]
Ah, awesome!

That answers my questions! Thanks Jim! :)

Would you like any help on the readme? Otherwise I can close this issue.
