### ISSUE TITLE
Non-deterministic error is not printed

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/bench#28]
Reprex:

```r
bench::mark(if (runif(1) < 0.01) stop("stop"))
```
nothing is printed here...

Somewhat surprisingly, the  error is actually there, you can catch it:
```r
tryCatch(bench::mark(if (runif(1) < 0.01) stop("stop")), error = identity)
#> <simpleError in force(expr): stop>
```

**Comment by jimhester** [comment]
I can reproduce it, no clue what is happening though, it is quite weird.
