### ISSUE TITLE
plot() merges `{` calls but summary() does not 

### ISSUE THREAD

**Issue by courtiol** [r-lib/bench#40]
Hi all,
There seem to be an issue when plotting the outcome of a benchmark involving `{`.
That is a pity because `{` are useful to introduce multiline calls on the fly.
Here is an example:

```{r}
res_bench <- mark(
  {
    a <- 1 + 1
    b <- a + 1
  },
  {
   `<-`(a, `+`(1, 1))
   `<-`(b, `+`(a, 1))
  })
plot(res_bench)
```
![image](https://user-images.githubusercontent.com/7499666/52086357-f4995880-25a6-11e9-8338-aa041c09e55a.png)

This is only a plotting issue since the summary table displays fine:

```{r}
res_bench
```

```{r}
# A tibble: 2 x 14
  expression   min  mean median     max `itr/sec` mem_alloc  n_gc n_itr total_time result memory
  <chr>      <bch> <bch> <bch:> <bch:t>     <dbl> <bch:byt> <dbl> <int>   <bch:tm> <list> <list>
1 {...       350ns 727ns  745ns  44.9µs  1375154.        0B     0 10000     7.27ms <dbl … <Rpro…
2 {...       346ns 748ns  445ns 188.4µs  1336612.        0B     0 10000     7.48ms <dbl … <Rpro…
# … with 2 more variables: time <list>, gc <list>
```

Best,

Alex

**Comment by jimhester** [comment]
This is going to be pretty hard to fix unfortunatly due to the way ggplot2 handles groups.

However you can remove the ambiguity by naming the expressions, e.g.

``` r
library(bench)
res_bench <- mark(
  infix = {
    a <- 1 + 1
    b <- a + 1
  },
  polish = {
   `<-`(a, `+`(1, 1))
   `<-`(b, `+`(a, 1))
  })
plot(res_bench)
```

![](https://i.imgur.com/7rFkl0K.png)

<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
