### ISSUE TITLE
bench::mark does not work well with progress bars 

### ISSUE THREAD

**Issue by mem48** [r-lib/bench#45]
Functions with progress bars run twice and take twice as long as necessary to run

A simple example

```
func1 <- function(x){
  pbapply::pblapply(1:x,function(x){
    Sys.sleep(1)
    return(x)
  })
}

t1 <- Sys.time()
bench::mark(check = FALSE,
            f1 = func1(5),
            f2 = func1(10))
t2 <- Sys.time()
difftime(t2,t1)
```
This should show 2 progress bars and take 15 seconds, but shows 4 bars and takes 30 seconds

**Comment by jimhester** [comment]
The progress bar is tangential, `bench::mark()` first runs each expression once to measure the memory allocations and store the results, then runs additional times to measure the execution time.

If you just want to measure execution time you can use `bench::system_time()`.
