### ISSUE TITLE
unnest method

### ISSUE THREAD

**Issue by hadley** [r-lib/bench#48]
Just a heads up to let you know that you'll need a new unnest method for dev tidyr since the interface has changed a bit.

**Comment by ginolhac** [comment]
yes, right now it breaks `autoplot`, using CRAN `tidyr` v0.8.3 works fine

**Comment by jimhester** [comment]
https://github.com/tidyverse/tidyr/blob/ef87abe14215a885365d2ae67bc6fb6a39287466/revdep/problems.md#bench
