### ISSUE TITLE
Avoid Error in eval(e, env): argument is missing, with no default ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/bench#61]
With benchmarks we're always adding, removing, moving around calls, this issue has me scratching my head every time and I can't seem to get my head around it.

``` r
bench::mark(
  1+3,
  2+2,
)
#> Error in eval(e, env): argument is missing, with no default
```

It comes from the trailing comma of course, but it's not always that easy to spot, can we have either an error message that suggests the possible mistake that was made, or (better in my view), allow missing arguments and ignore them ?

**Comment by jimhester** [comment]
Probably the easiest thing would be to use `rlang::list2()` / `dots_list()`, which does this automatically.

**Comment by lionel-** [comment]
I think we should revert this. `enexprs()` and `enquos()` use metaprogramming splicing, which transforms objects into a pairlist. This is different to value-based splicing used in `list2()` or `vec_cast_common()` which doesn't disaggregate list inputs. This has performance implications:

```r
x <- as.list(1:1e5)
foo <- function(x) list2(!!!x)

bench::mark(
  lang = list2(!!!x),
  value = foo(x)
)[1:8]
#> # A tibble: 2 x 8
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 lang         41.8ms  44.73ms      21.7     781KB     2.17    10     1
#> 2 value        1.58ms   1.79ms     560.      781KB     8.74   256     4
```

**Comment by lionel-** [comment]
@romainfrancois I think this explains the performance difference you observed in your vctrs benchmarks.
