### ISSUE TITLE
Feature request: Make first result error optional

### ISSUE THREAD

**Issue by wetlandscapes** [r-lib/bench#65]
My impression of the error "Each result must equal the first result..." is that it checks that the two expressions are generating the same result. That is great, but I'm trying to benchmark some bootstrapping functions between pure R and Rcpp. In that context, I wouldn't expect the results to be the same across iterations (if that is what's going on). Thus, I think it might make more sense for the "equal" behavior to be default, but to still provide users with the ability to bench more code that might return random results (if I'm understanding things correctly).

In any case, this is a really cool and thoughtful package. Thanks for taking the time to put it together!

**Comment by jimhester** [comment]
You can use `check = FALSE` to disable checking the outputs for equality, or provide a boolean function if you want a looser check.
