### ISSUE TITLE
Adaptive stopping procedure

### ISSUE THREAD

**Issue by hadley** [r-lib/bench#7]
You could imagine a procedure where rather than giving a fixed number of runs you give a desired estimation precision, and the test is run until that precision is reached.

**Comment by jimhester** [comment]
This is the way that https://github.com/google/benchmark works by default. It is tempting to use that, but you would likely have to bundle the library in the package and maybe it is too much for this usecase.

**Comment by jimhester** [comment]
Decided the benchmark package was too heavy by default. I ended up doing the stopping based on time taken (default .5 seconds) rather than precision, but we can do something more sophisticated if we want to.

**Comment by hadley** [comment]
Maybe it's better to address this by describing a little bit about good experimental design. Maybe something along these lines:

There are two major sources of variability in benchmark times: garbage collection and system utilisation. Garbage collection means that some fraction of runs take much longer than other runs. It's somewhat naive to simply ignore these timings, because it's important to fairly account for expressions that allocate many more objects, and hence create longer gc times. The bench package controls for GC by running each expression multiple times, making it possible to amortise cost across multiple runs.

The microbenchmark package controls for system utilisation by randomising the run order of each individual expression. This randomises over system usage, but means that GCs can no longer be easily allocated to a specific expression and hence amortised.  The bench package is optimised for the gc case, so you'll need to control for system utilisation some other way. We recommend...

**Comment by jennybc** [comment]
What if this package selected a random order for the expressions? Then if you ran the whole study a couple of times and row-bound the results, you get an exploration of different orderings "for free".

**Comment by hadley** [comment]
Having used `bench::mark()` for a bit, I think the existing adaptivity is adequate
