### ISSUE TITLE
Installing bench gives a warning for prior installation of non-existent 'glue' package

### ISSUE THREAD

**Issue by Anirban166** [r-lib/bench#76]
Installing bench makes conflicts with the 'glue' package, which isn't installed at any moment, but the warning given is 'cannot remove prior installation of 'glue' package.

I tried to remove it but it was never installed and as an extra step I checked in the packages section for any package by the name of 'glue' as well but didn't found any and this error pops up everytime I try to install bench via:
devtools::install_github("r-lib/bench")

![Image describing my case](https://user-images.githubusercontent.com/30123691/77887130-ab669680-7287-11ea-84ff-a45a7f1c762a.png)

**Comment by jimhester** [comment]
glue is a dependency of devtools. install bench with `remotes::install_github()` instead of using devtools directly.
