### ISSUE TITLE
Consistent time units (by default)

### ISSUE THREAD

**Issue by engineerchange** [r-lib/bench#80]
Bench currently mixes time units when displaying performance statistics; request a feature to make the reporting consistent by the data across all rows/columns, by default.

Stealing from @dcooley's mention [here](https://github.com/csgillespie/efficientR/issues/264#issuecomment-626393865). He also references [this github comment](https://github.com/Rdatatable/data.table/issues/1717#issuecomment-626299686).

```
library(bench)


foo <- function() Sys.sleep(5)
bar <- function() Sys.sleep(0.1)

bench::mark(foo(), bar())

# # A tibble: 2 x 13
# expression          min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result memory           time     gc              
# <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list> <list>           <list>   <list>          
#   1 foo()            5s       5s     0.200        0B        0     1     0         5s <NULL> <df[,3] [0 × 3]> <bch:tm> <tibble [1 × 3]>
#   2 bar()         100ms    100ms     9.92         0B        0     5     0      504ms <NULL> <df[,3] [0 × 3]> <bch:tm> <tibble [5 × 3]>
```

**Comment by jimhester** [comment]
This is what the time_unit argument is for. If you want consistent units in the display specify what unit you want them displayed in.

**Comment by dcooley** [comment]
I think @engineerchange was asking if it's possible to make the consistent units the default, rather than mixing them by default.
