### ISSUE TITLE
autoplot seems to ignore ordering of factor levels in expression

### ISSUE THREAD

**Issue by fjodor** [r-lib/bench#82]
Tried to order by execution time as suggested in ?autoplot.bench_mark(). y axis categories not in that order. Apparently ordered alphabetically, as if factor levels are re-assigned in autoplot() call.

dat <- data.frame(x = runif(10000, 1, 1000), y=runif(10000, 1, 1000))

res <- bench::mark(
  dat[dat$x > 500, ],
  dat[which(dat$x > 500), ],
  subset(dat, x > 500))

res <- res %>%
  mutate(expression = forcats::fct_reorder(as.character(expression), min, .desc = TRUE)) %>%
  as_bench_mark()

levels(res$expression)
autoplot(res, "violin")

**Comment by jimhester** [comment]
Thanks! This feature was inadvertently removed, it should now work as intended and described in the example.
