### ISSUE TITLE
vec_slice() for bench_expr

### ISSUE THREAD

**Issue by krlmlr** [r-lib/bench#85]
``` r
x <- bench:::new_bench_expr(list(quote(1), quote(2)))
x[1]
#> [[1]]
#> [1] 1
#> 
#> attr(,"description")
#> [1] ""
vctrs::vec_slice(x, 1)
#> [[1]]
#> [1] 1
#> 
#> attr(,"description")
#> [1] "" ""
```

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

CC @lionel-.

**Comment by krlmlr** [comment]
`vec_proxy.bench_expr()` was introduced in #64, do we still need it? It works for me when I revert, CC @romainfrancois.

**Comment by lionel-** [comment]
If description is a vectorised attribute, it should be included as a column in a data frame proxy.
