### ISSUE TITLE
bench::mark() does not return the summary when run from bench::cb_run()

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/bench#96]
The output of `bench::mark()` is not the same depending on whether it is ran interactively or from `bench::cb_run()`.
I can think of scenarios where it is useful to have the output of `bench::mark()` as a direct return value when ran with `bench::cb_run()` because it's more detailed and can be used with `autoplot()` for example. Was this a deliberate design decision to not return it in [the source code](https://github.com/r-lib/bench/blob/master/R/mark.R#L137-L142):
```r
out <- summary(bench_mark(tibble::as_tibble(results, .name_repair = "minimal")), 
        filter_gc = filter_gc, relative = relative, time_unit = time_unit)
    file <- getOption("bench.file", NULL)
    if (!is.null(file)) {
        cb_write(out, file)
    } else {
        out
    }
```
Tracking down return values with `cb_write()` -> `append_file_to_git_notes()` -> `git()` does not seem to have a particularly informative return value (I think always `NULL` if not an error).
I'd suggest to return `out` in the above code snippet in any case. I can make a PR if you want.

**Comment by jimhester** [comment]
sure, though it should probably be returned invisibly in that case.
