### ISSUE TITLE
Memory profiling unavailable on Linux-x86_64-fedora (Clang/GCC) & Solaris-x86 

### ISSUE THREAD

**Issue by Anirban166** [r-lib/bench#98]
Hi, this issue arises with calls to `bench_memory()`, and it is precisely [this issue](https://github.com/r-lib/bench/issues/56), but on some specific machines:

- r-devel-linux-x86_64-fedora-clang
- r-devel-linux-x86_64-fedora-gcc
- r-patched-solaris-x86

Whats the best way to skip them on these particular systems?

**Comment by jimhester** [comment]
Check if R has memory profiling, e.g. `if (capabilities("profmem"))`

**Comment by Anirban166** [comment]
Thanks!
